### ISSUE TITLE
Duplicate diagrams on the article

### ISSUE THREAD

**Issue by boraozgen** [Ralim/STM32-DMA-TIM-WS2812#2]
Hi Ben,

thanks for the article:

https://ralimtek.com/posts/2021/ws2812/

I assume that the last two diagrams are duplicates of the first diagram. Can you please fix the diagrams to show the actual DMA procedure?

Cheers

**Comment by Ralim** [comment]
Apologies for missing this.
Have pushed new image assets now; should go live in a few minutes or so.
